# task config
task: hierarchical_singlecombat_lock

# simulation config
sim_freq: 60
agent_interaction_steps: 12 # step 0.2s

# termination config
max_steps: 1000             # episode length: 200s
altitude_limit: 2500
radius_limit: 14.0
acceleration_limit_x: 10.0
acceleration_limit_y: 10.0
acceleration_limit_z: 10.0

# aircraft config
aircraft_configs: {
  A0100: {
    color: Red,
    model: f16,
    init_state: {
      ic_long_gc_deg: 120.05,
      ic_lat_geod_deg: 59.92,
      ic_h_sl_ft: 20000,
      ic_psi_true_deg: 0,
      ic_u_fps: 800.0,
    },
    missile: 0
  },
  B0100: {
    color: Blue,
    model: f16,
    init_state: {
      ic_h_sl_ft: 20000,
      ic_lat_geod_deg: 60.08,
      ic_long_gc_deg: 119.95,
      ic_psi_true_deg: 180.0,
      ic_u_fps: 800.0,
    },
    missile: 0
  }
}

# lock_info
max_lock_angle: 20        # unit: degree
max_lock_distance: 5000  # unit: m
min_lock_distance: 2000   # unit: m
min_attack_interval: 125     # unit: step
min_lock_step: 10
min_shoot_step: 25

# (lontitude, latitude, altitude)
battle_field_center: [120.0, 60.0, 0.0]

# battle boundary info
BoundaryReward_safe_radius: 12.5      # km
BoundaryReward_danger_radius: 13.0    # km